### ISSUE TITLE
Manipulating headers

### ISSUE THREAD

**Issue by mhkolk** [Farfetch/kafkaflow#518] opened 2024-02-04 17:27 UTC
### Is your request related to a problem you have?

Is there any way to manipulate eg. remove certain header, for instance Message-Type, currently? 

I tried doing that from within middleware. `IMessageContext.Headers` is read only, IEnumerable collection which makes it impossible to remove headers or replace the entire collection with something else.

### Describe the solution you'd like

Make `IMessageContext.Headers` settable or introduce method to remove headers

### Are you able to help bring it to life and contribute with a Pull Request?

No

**Comment by mhkolk** [comment] 2024-02-04 17:49
Using `context.Headers.SetString("Message-Type", string.Empty)` works as a workaround for erasing specific headers but will leave this open for proper solution.

**Comment by lpcouto** [comment] 2024-02-06 15:25
Hi @mhkolk ,

**Comment by lpcouto** [comment] 2024-02-06 15:32
Hi @mhkolk ,
Headers were defined as read-only by design, as they represent the message headers, which should not be editable; as an example of the same design principle, you can look at `HttpRequestMessage`.
In the `IMessageContext`, you have the `Items` property, a dictionary, that you can use as a bag, adding there some data you may find useful for the message context.

**Comment by mhkolk** [comment] 2024-02-06 15:37
If we're using KafkaFlow for producing and have the ability to use middleware to manipulate messages I think it makes sense to allow manipulating headers (on the producer side). Developer using KF should be responsible for proper usage.

**Comment by mhkolk** [comment] 2024-02-06 15:38
> In the `IMessageContext`, you have the `Items` property, a dictionary, that you can use, adding there some data you may find useful for the message context.

This was more about removing stuff than adding. The ability to add is already present

**Comment by joelfoliveira** [comment] 2024-02-06 19:04
Hi @mhkolk, 

The reason the headers collection does not allow that kind of manipulation is that it can introduce dependencies between the middlewares which is not something to encourage, since it is expected that the header collection represents the headers present in the Kafka message.

Is there any use case where the current implementation is blocking you from using KafkaFlow?

**Comment by mhkolk** [comment] 2024-02-07 07:46
It was just a suggestion, I worked around it by using `SetString`, so it is not a blocker.

**Comment by joelfoliveira** [comment] 2024-02-07 10:05
Thank you for the feedback @mhkolk.

In the future, if this question is raised again we can revisit this subject, but for now, we should leave it as-is. 

We will be closing this issue. Please feel free to respond to this message or reopen the issue if you'd like to continue the discussion or if you've encountered any new developments related to it.

Thank you for your contribution.

**Closed by joelfoliveira** 2024-02-07 10:05 UTC
Labels: enhancement
